### ISSUE TITLE
New Install - Issues when running latest plugin

### ISSUE THREAD

**Issue by kevsterd** [imcfarla2003/domoticz-hive#6]
Installing the latest build on the latest beta of Domoticz, I get the following once the 'hardware' is added:

```
2018-12-10 20:56:02.848  Error: Hive hardware (13) thread seems to have ended unexpectedly
2018-12-10 20:56:15.629  Status: (Hive) Stop directive received.
```

Then all of the hardware watchdogs and the Pi itself grinds to a halt.

```
2018-12-10 20:56:30.854  Error: domo1 motherboard hardware (6) thread seems to have ended unexpectedly
2018-12-10 20:56:44.858  Error: domo1 motherboard hardware (6) thread seems to have ended unexpectedly
2018-12-10 20:56:58.861  Error: domo1 motherboard hardware (6) thread seems to have ended unexpectedly
2018-12-10 20:57:02.282  Status: Notification sent (Email)
2018-12-10 20:57:12.865  Error: domo1 motherboard hardware (6) thread seems to have ended unexpectedly
2018-12-10 20:57:26.868  Error: WebServer:8080 thread seems to have ended unexpectedly (last update 73.000000 seconds ago)
2018-12-10 20:57:26.868  Error: Domoticz(31344) is exiting due to watchdog triggered...
```

Can't get it to run well enough to enable debug mode.   I did notice it did not add any 'hive' named devices.  Should it ?

Thanks

**Comment by kevsterd** [comment]
Actually just got this mailed to me from my install once I removed the plugin....
`2018-12-10 21:03:24.301 Error: (HivePlug) failed to load 'plugin.py', Python Path used was ':/usr/lib/python3.4/:/usr/lib/python3.4/plat-arm-linux-gnueabihf:/usr/lib/python3.4/lib-dynload'.
2018-12-10 21:03:24.301 Error: (Hive) Module Import failed, exception: 'ImportError'
2018-12-10 21:03:24.301 Error: (Hive) Module Import failed: ' Name: plugin'
`

Not sure of the exact cause...

**Comment by imcfarla2003** [comment]
Have you got python urllib installed?

**Comment by kevsterd** [comment]
Ahh forgot Domoticz uses Python 3, and had been checking against default Python 2.7 install on Raspian.

According to various sites urllib is a default module in Python 3.x so it should just work.

Is there any way to run the plugin Python script in debug mode outside of Domoticz ?

**Comment by imcfarla2003** [comment]
You can run it but it depends on a module called Domoticz which means that
it will fail before doing anything useful.

I was thinking last night to mock up a file that does nothing so we can
test outside of Domoticz.  It would help me as then I can use the JSON
files people send me without affecting my own system 

Cheers,

Iain

On 16 Dec 2018 15:50, kevsterd <notifications@github.com> wrote:

> Ahh forgot Domoticz uses Python 3, and had been checking against default
> Python 2.7 install on Raspian.
>
> According to various sites urllib is a default module in Python 3.x so
> it should just work.
>
> Is there any way to run the plugin Python script in debug mode outside
> of Domoticz ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub[1], or mute the
thread[2].
>
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/imcfarla2003/domoticz-hive","title":"imcfarla2003/domoticz-hive","subtitle":"GitHub
repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open
in
GitHub","url":"https://github.com/imcfarla2003/domoticz-hive"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kevsterd
in #6: Ahh forgot Domoticz uses Python 3, and had been checking against
default Python 2.7 install on Raspian.\r\n\r\nAccording to various sites
urllib is a default module in Python 3.x so it should just work.\r\n\r\nIs
there any way to run the plugin Python script in debug mode outside of
Domoticz ?"}],"action":{"name":"View
Issue","url":"https://github.com/imcfarla2003/domoticz-hive/issues/6#issuecomment-447653484"}}}
[ { "@context": "http://schema.org", "@type": "EmailMessage",
"potentialAction": { "@type": "ViewAction", "target":
"https://github.com/imcfarla2003/domoticz-hive/issues/6#issuecomment-447653484",
"url":
"https://github.com/imcfarla2003/domoticz-hive/issues/6#issuecomment-447653484",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } }
> ]



Links:
------
[1]  
https://github.com/imcfarla2003/domoticz-hive/issues/6#issuecomment-447653484
[2]

**Comment by imcfarla2003** [comment]
Re: Is there any way to run the plugin Python script in debug mode outside of Domoticz ?

I have just added a test folder which implements a Domoticz.py and a test.py suitable for testing outside of Domoticz.

if you change to the test directory and run python3 test.py <Hive username> <Hive Password>
This will connect to hive and create mock representations of your devices

**Comment by kevsterd** [comment]
Cool.  Just tried it (appreciate the help and hoping it will aid others).  Running:

`python3 ./test.py me mypass

Starting
Log: Starting
Debug Level: 1
Log: DomoticzVersion Available 4.10263
Debug: Domoticz Revision: 10263
Log: TimedOut available
Log: Creating Session
Debug: --REMOVED--
Debug: onHeartbeat called
Debug: Getting Data
Debug: Getting Temperatures
Debug: Temp = 17.8
Debug: Target = 17.0
Debug: Heating = OFF
Debug: Getting Battery Status
Debug: Battery = 100
Debug: RSSI = 6.0
Debug: Updating Devices
New Device: Thermostat 1_Current
Create Device: Thermostat 1_Current
New Device: Thermostat 1_Target
Create Device: Thermostat 1_Target
New Device: f83975e5-f79b-4449-8665-65e2b4f4f975
Create Device: f83975e5-f79b-4449-8665-65e2b4f4f975
New Device: f83975e5-f79b-4449-8665-65e2b4f4f975
Create Device: f83975e5-f79b-4449-8665-65e2b4f4f975
New Device: 7e7259bb-e70d-490a-95c2-b36a547359b7
Create Device: 7e7259bb-e70d-490a-95c2-b36a547359b7
New Device: Hive_Outside
Create Device: Hive_Outside
Devices
    Thermostat 1 - Current
    Thermostat 1 - Target
    Thermostat 1 - Heating
    Thermostat 1 - Thermostat
    HotWater - Relay
    Outside
Stopping
Log: Deleting Session
`

So from the debug it appears to connect the the Hive API and pull data.   Should the values be output however ?

**Comment by imcfarla2003** [comment]
Everything looks good.
The plugin works properly - now you just need to work out why it doesn't work when run with domoticz.
I would suggest building domoticz yourself then everything should work.

**Comment by kevsterd** [comment]
So it appears when I install the plugin into Domoticz I still get a load of errors thrown

`2018-12-18 17:50:43.132 Error: Hive hardware (13) thread seems to have ended unexpectedly
2018-12-18 17:50:57.135 Error: domo1 motherboard hardware (6) thread seems to have ended unexpectedly
2018-12-18 17:50:57.135 Error: Hive hardware (13) thread seems to have ended unexpectedly
`

The Pi is not that busy.   Top 6 processes for example:

```
17:55:03 up 6 days,  1:58,  1 user,  load average: 0.09, 0.07, 0.08
Tasks:  98 total,   1 running,  60 sleeping,   0 stopped,   0 zombie
%Cpu(s): 11.0 us,  5.1 sy,  0.0 ni, 83.6 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem:   1000180 total,   761964 used,   238216 free,    58588 buffers
KiB Swap:   102396 total,        0 used,   102396 free.   564268 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
28506 root      20   0  263824  26304  18040 S  28.1  2.6   0:11.16 domoticz
 1229 root      20   0   31176  21836   1312 S   7.9  2.2 647:28.57 rtl_433
  115 root      20   0   10268   5536   5280 S   0.3  0.6   0:25.94 systemd-journal
  411 root      20   0   44872  31580   6896 S   0.3  3.2  36:24.88 amazon-dash
  681 root      20   0  938656  33160  24140 S   0.3  3.3  53:30.91 dockerd
  789 root      20   0  905348   8436   6268 S   0.3  0.8  33:37.12 docker-container

```
Also checking devices, I can't see any new devices added so it appears it does not expose them for me.  What do they get added as (type/name etc)

I could build my own, however I'm running the latest beta (and have done for three years or so) and it works fine for me for everything else so am loathed to do do it.

I appreciate any help you can give me as it looks to be a great plugin.

**Comment by imcfarla2003** [comment]
When you run Domoticz what version of python does it say?  

What version of python do you have installed on the pi?

I suspect a mismatch.

The devices will be named as per the test but with a prefix:
Hive - Thermostat 1 - Current 
Hive - Thermostat 1 - Target 
Hive - Thermostat 1 - Heating 
Hive - Thermostat 1 - Thermostat 
Hive - HotWater - Relay Outside

You do have the settings set to allow new devices?

**Comment by kevsterd** [comment]
So
Domo Python version:
`2018-12-18 18:08:00.298 Status: PluginSystem: Started, Python version '3.4.2'.`

Python on the Pi:
`#python --version
Python 2.7.9
`
`#python3 --version
Python 3.4.2
`

Ahh, good point about new devices.   Pesky neighbours have some odd devices so I leave it turned off.  Ill try again now

TIA

**Comment by kevsterd** [comment]
OK.  trying again, still same results.  I did have new devices allowed.

Looking though the logs I see
```
2018-12-18 19:32:09.745  Status: (Hive) Started.
2018-12-18 19:32:09.746  Status: EventSystem: reset all events...
2018-12-18 19:32:09.747  Status: EventSystem: reset all device statuses...
2018-12-18 19:32:09.975  Status: PluginSystem: Entering work loop.
2018-12-18 19:32:10.077  Status: Python EventSystem: Initalizing event module.
2018-12-18 19:32:10.078  Status: EventSystem: Queue thread started...
2018-12-18 19:32:10.078  Status: EventSystem: Started
2018-12-18 19:32:10.204  Error: (HivePlug) failed to load 'plugin.py', Python Path used was ':/usr/lib/python3.4/:/usr/lib/python3.4/plat-arm-linux-gnueabihf:/usr/lib/python3.4/lib-dynload'.
2018-12-18 19:32:10.204  Error: (Hive) Module Import failed, exception: 'ImportError'
2018-12-18 19:32:10.204  Error: (Hive) Module Import failed: ' Name: plugin'
2018-12-18 19:32:10.204  Error: (Hive) Error Line details not available.
```
Ill take a look though the plugin code to see if I can work out whats causing that error.   I did try setting the Hardware device to debug but couldn't see much more.

**Comment by kevsterd** [comment]
Not really getting anywhere now.

Just tried again with max permissions on the plugin just in case !

`2018-12-19 15:04:16.052  Status: (Hive) Started.
2018-12-19 15:04:16.390  Error: Domoticz(pid:8391, tid:8397('PluginMgr')) received fatal signal 11 (Segmentation fault)
2018-12-19 15:04:16.390  Error: siginfo address=0x334, address=0x7229b0
2018-12-19 15:04:19.968  Error: Thread 24 (Thread 0x75272430 (LWP 8397)):
2018-12-19 15:04:19.968  Error: #0  0x76eebef8 in __libc_waitpid (pid=8608, stat_loc=0x7526f6b8, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
2018-12-19 15:04:19.968  Error: #1  0x002c92e0 in dumpstack_gdb(bool) ()
2018-12-19 15:04:19.968  Error: #2  0x002c98cc in signal_handler(int, siginfo_t*, void*) ()
2018-12-19 15:04:19.968  Error: #3  <signal handler called>
2018-12-19 15:04:19.969  Error: #4  0x00000334 in ?? ()
2018-12-19 15:04:19.969  Error: #5  0x007229b0 in EVP_MD_CTX_reset ()
2018-12-19 15:04:19.969  Error: #6  0x00722f70 in EVP_MD_CTX_copy ()
2018-12-19 15:04:19.969  Error: #7  0x67dd0a5c in ?? () from /usr/lib/python3.4/lib-dynload/_hashlib.cpython-34m-arm-linux-gnueabihf.so`

**Comment by imcfarla2003** [comment]
Hello,

Can you try using plugin.new.py just copy it into your Hive plugin directory and rename it to plugin.py

I have updated it today to have feature parity to the old style plugin.

**Comment by kevsterd** [comment]
Hi

Thanks for you persistance.   Looks like its working now 👍 

View from my Domo is

![image](https://user-images.githubusercontent.com/18176387/50786809-7e0d8180-12ac-11e9-916d-9530d31eba7d.png)

Anything else you need me to test ?

**Comment by kevsterd** [comment]
Seems to work ok, but threw a couple of errors:
```

2019-01-07 18:51:04.067 Error: (Hive) 'onMessage' failed 'UnboundLocalError':'local variable 'thermostat_battery' referenced before assignment'.
2019-01-07 18:51:04.067 Error: (Hive) ----> Line 826 in '/home/XX/domoticz/plugins/Hive/plugin.py', function onMessage
2019-01-07 18:51:04.067 Error: (Hive) ----> Line 156 in '/home/XX/domoticz/plugins/Hive/plugin.py', function onMessage
2019-01-07 18:51:04.067 Error: (Hive) ----> Line 286 in '/home/XX/domoticz/plugins/Hive/plugin.py', function UpdateDeviceState

```

**Comment by kevsterd** [comment]
and

`2019-01-07 18:54:25.222 Error: (Hive): Async Secure Read Exception: 1, stream truncated`

**Comment by imcfarla2003** [comment]
The referenced before assignment should be fixed now.

What was happening when you got the stream truncated? - that normally is a "bad request" i.e. I haven't got something right...

**Comment by kevsterd** [comment]
OK.  Pulled new version and installed.

Still getting Async error.  I wacked the Hive debug up to full

`2019-01-08 07:14:36.076 (Hive) onHeartbeat called
2019-01-08 07:14:36.076 (Hive) Counter = 6
2019-01-08 07:14:46.915 (Hive) 70 6f 72 74 65 64 56 61 6c 75 65 22 3a 2d 35 39 2c 22 64 69 portedValue":-59,"di
.....
2019-01-08 07:14:46.922 (Hive) 2c 22 72 65 70 6f 72 74 43 68 61 6e 67 65 64 54 69 6d 65 22 ,"reportChangedTime"
2019-01-08 07:14:46.922 (Hive) 3a 31 35 34 33 32 32 36 35 33 31 35 33 36 7d 7d 7d 5d 7d 0d :1543226531536}}}]}.
2019-01-08 07:14:46.922 (Hive) 0a .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .
2019-01-08 07:14:46.923 (Hive) Processing 'ReadEvent' message
2019-01-08 07:14:46.923 (Hive) Received 5 bytes of data
2019-01-08 07:14:46.923 (Hive) 30 0d 0a 0d 0a .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 0....
2019-01-08 07:14:46.925 (Hive) Pushing 'onMessageCallback' on to queue
2019-01-08 07:14:46.925 (Hive) Processing 'onMessageCallback' message
2019-01-08 07:14:46.925 (Hive) Calling message handler 'onMessage'.
2019-01-08 07:14:46.925 (Hive) onMessage called for Hive Devices
2019-01-08 07:14:46.934 (Hive) Pushing 'DisconnectDirective' on to queue
2019-01-08 07:14:46.934 (Hive) Getting Temperatures
2019-01-08 07:14:46.938 (Hive) Temp = 17.35
2019-01-08 07:14:46.938 (Hive) Target = 17.0
2019-01-08 07:14:46.938 (Hive) Heating = OFF
2019-01-08 07:14:46.938 (Hive) Getting Battery Status
2019-01-08 07:14:46.943 (Hive) Only one thermostatui node so using that
2019-01-08 07:14:46.943 (Hive) Battery = 100
2019-01-08 07:14:46.944 (Hive) RSSI = 7.08
2019-01-08 07:14:46.944 (Hive) Updating Devices
2019-01-08 07:14:46.944 (Hive - Hive - Current) Updating device from 17:'17.35' to have values 17:'17.35'.
2019-01-08 07:14:46.947 (Hive - Hive - Target) Updating device from 17:'17.0' to have values 17:'17.0'.
2019-01-08 07:14:46.949 (Hive - Hive - Thermostat) Updating device from 17:'17.0' to have values 17:'17.0'.
2019-01-08 07:14:46.977 (Hive) Processing 'DisconnectDirective' message
2019-01-08 07:14:46.977 (Hive) Disconnect directive received for 'api.prod.bgchprod.info:443'.
2019-01-08 07:14:46.977 (Hive) Handling TCP disconnect, socket (api.prod.bgchprod.info:443) is connected
2019-01-08 07:14:46.978 (Hive) Pushing 'DisconnectedEvent' on to queue
2019-01-08 07:14:46.978 (Hive) Processing 'DisconnectedEvent' message
2019-01-08 07:14:46.978 (Hive) Disconnect event received for 'api.prod.bgchprod.info:443'.
2019-01-08 07:14:46.978 (Hive) Pushing 'onDisconnectCallback' on to queue
2019-01-08 07:14:46.979 (Hive) Processing 'onDisconnectCallback' message
2019-01-08 07:14:46.979 (Hive) Calling message handler 'onDisconnect'.
2019-01-08 07:14:46.979 (Hive) onDisconnect called
2019-01-08 07:14:46.624 Error: (Hive): Async Secure Read Exception: 1, stream truncated
2019-01-08 07:14:46.978 Error: (Hive): Async Secure Read Exception: 1, stream truncated
2019-01-08 07:14:56.074 (Hive) Pushing 'onHeartbeatCallback' on to queue
2019-01-08 07:14:56.096 (Hive) Processing 'onHeartbeatCallback' message
2019-01-08 07:14:56.096 (Hive) Calling message handler 'onHeartbeat'.
2019-01-08 07:14:56.096 (Hive) onHeartbeat called
2019-01-08 07:14:56.096 (Hive) Counter = 2
`

Domo at this point is not doing anything special, just a lot of listening !

HTH

**Comment by imcfarla2003** [comment]
The Async Secure Read Exceptions are happening in the base domoticz plugin transport code and I can not do anything about them - they don't seem to be fatal and the plugin works ok even with the errors.

Can you monitor and see if things work ok for you?

**Comment by kevsterd** [comment]
Hi - seems to work fine.   Odd labling scheme with the devices but can sort that.   I have had to disable it for now as its spaming my email every minute with the error however.   Ill do a bit of testing to see if I can establish what the error is...  thx
